---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: flagger
  namespace: istio-system
spec:
  interval: 10m
  timeout: 5m
  dependsOn:
    - name: istiod
      namespace: istio-system
    - name: prometheus
      namespace: monitoring
  chart:
    spec:
      chart: flagger
      version: '>=1.37.0 <2.0.0'
      sourceRef:
        kind: HelmRepository
        name: flagger
        namespace: flux-system
      interval: 5m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    meshProvider: istio
    metricsServer: http://prometheus-server.monitoring:80
    logLevel: info
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 1000m
        memory: 512Mi
